//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: MySecondProto.proto
namespace PB
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MySecondProto")]
  public partial class MySecondProto : global::ProtoBuf.IExtensible
  {
    private global::ProtoBuf.IExtension extensionObject;
	global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
     { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
    public MySecondProto() {}
    
    private string _name = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _plotId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"plotId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int plotId
    {
      get { return _plotId; }
      set { _plotId = value; }
    }
    private int _page_number = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"page_number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int page_number
    {
      get { return _page_number; }
      set { _page_number = value; }
    }
    private int _results_per_page = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"results_per_page", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int results_per_page
    {
      get { return _results_per_page; }
      set { _results_per_page = value; }
    }
  }
  
}